### ISSUE TITLE
Evaluate Formsy

### ISSUE THREAD

**Issue by kurund** [kurund/glific-webapp#11]
https://www.npmjs.com/package/formsy-react

**Comment by claalmve** [comment]
I think Formsy is a really clean way to validate inputs, but I can't find a way to get around one slight issue. Whenever you render the page for the first time, the inputs are by default empty. Therefore, the errors are thrown, even though the user hasn't even input any information yet. I figured that this wasn't the best UX (only throwing errors until after the user inputs something and validating their input), but couldn't find a good workaround for that initial render.

One thing I tried was inputting a default value of a single space (" "), but I think this might lead to more confusion down the line if we have to slice the different inputs every time.

**Comment by claalmve** [comment]
Never mind! I found a way around this issue-- I just used Material-UI's `required` prop and that behaved as intended for me.

**Comment by kurund** [comment]
@claalmve Initial integration looks good. I will file detailed issues for improvement on glific repo.
