### ISSUE TITLE
Code structuring of GraphQL queries

### ISSUE THREAD

**Issue by rathorevaibhav** [kurund/glific-webapp#18]
### Overview
In the current code, GQL queries reside in the container components. This is not the best way as it may lead to code duplicity for query definitions.

We also need to research/read on the best practices to make API calls from React components and explore a structure that the community recommends.

### Dev notes
- Maybe this tutorial can give an idea on how to structure:
https://www.howtographql.com/react-apollo/0-introduction/
- Check if we can structure using actions, reducers etc. using the Redux convention

**Comment by kurund** [comment]
Moved this issue to https://github.com/glific/glific-frontend/issues/9
