### ISSUE TITLE
Convert UI components to functional components

### ISSUE THREAD

**Issue by rathorevaibhav** [kurund/glific-webapp#20]
### Overview
We have several UI components like Button, Checkbox, Dropdown, TextField that use class-based component definition. For consistency purposes, we need to convert them to functional components.
```js
class TextFieldElement extends React.Component<TextFieldElementProps> {
```

### Acceptance criteria
- All the UI elements are functional components
- The functionality works as expected. No breaking changes.

**Comment by kurund** [comment]
Moved to glific repo: https://github.com/glific/glific-frontend/issues/7
